### PR TITLE
Fix incorrect office entries in 2012 results

### PR DESCRIPTION
**Pull request by warwickmm**
This fixes several incorrect office entries by:
1. Finding candidates that were associated with 2 offices, "foo" and "bar".
2. If "foo" is obviously incorrect, replace all instances of "foo" in the office column with "bar".
3. Spot check some of the changes with internet search results.

This might not fix all of the problematic entries (for example, if a candidate is only associated with a bad value, or is associated with more than 2 offices).  However, this should hopefully still be an incremental improvement.

This fixes issue #35.

### CODE REVIEW

**Comment by warwickmm** [comment]
There are many files with this type of issue.  To encourage more careful review of the changes, I think I'll submit a separate pull request for each file.

**Comment by warwickmm** [comment]
I was able to semi-automate the fixes.  In total, there are around 126 files that required fixes.  Let me know if it's preferred to review these one at a time, or if I should include them all in a single pull request.

**Comment by dwillis** [comment]
@warwickmm you can aggregate them into a single PR.

**Comment by warwickmm** [comment]
Thanks @dwillis.  I've amended this pull request to include all the fixes.

**Pull request merged**
